create table CONVERSION_LOG(
ID INTEGER not null primary key,
URI VARCHAR(30) not null,
CREATION_DATE TIMESTAMP not null,
HTTP_RESPONSE_CODE INTEGER,
IP_ADDRESS VARCHAR(45),
COUNTRY_CODE VARCHAR(3),
ISP VARCHAR(100),
TIME_LAPSED INTEGER
);