create table CONVERSION_LOG(
ID INTEGER not null primary key,
CREATION_DATE TIMESTAMP not null,
IP VARCHAR(45),
URI VARCHAR(30) not null,
COUNTRY_CODE VARCHAR(3),
ISP VARCHAR(100),
HTTP_RESPONSE_CODE INTEGER,
TIME_LAPSED INTEGER
);